### ISSUE TITLE
Add World / Player Condition(s)

### ISSUE THREAD

**Issue by SFlakeZ** [xIRoXaSx/EnvironmentAdditions#24]
## Links
[eCloud - World](https://api.extendedclip.com/expansions/world/)
[eCloud - Player](https://api.extendedclip.com/expansions/player/)

# Player based placeholders
- [ ] `%world_name_<world>%` -> Allow different sounds per world
- [x] `%player_y%` -> Height might be interesting (in general for mountains)

**Comment by xIRoXaSx** [comment]
World conditions make totally sense, will add this capability :)

For height checks you can use the `Area` conditions like in the following example: 
```yaml
    Area:
      # ...
      Minimum:
        X: 0
        Y: 100
        Z: 0
      Maximum:
        X: 0
        Y: 320.0
        Z: 0
```
